- name: restart app
  command: /bin/true
  notify:
    - _stop app
    - _rebuild app
    - _start app
  when: app.autostart

- name: reload app
  command: /bin/true
  notify:
    - _restart app
  when: app.autostart

- name: _stop app
  sudo: true
  service: >
    name=app
    state=stopped

- name: _rebuild app
  command: >
    ./bin/build
    chdir={{ app.path }}

- name: _start app
  sudo: true
  service: >
    name=app
    state=started

- name: _restart app
  sudo: true
  service: >
    name=app
    state=restarted
