- name: restart app
  command: /bin/true
  notify:
    - _rebuild app
    - _restart app

- name: _rebuild app
  command: >
    ./bin/build
    chdir={{ app.path }}

- name: _restart app
  sudo: true
  service: >
    name=app
    state=restarted
