- name: add apt key
  sudo: true
  apt_key: >
    id=0x7BD9BF62
    url=http://nginx.org/keys/nginx_signing.key

- name: add apt repositories
  sudo: true
  apt_repository: >
    repo='{{ item }} http://nginx.org/packages/ubuntu/ trusty nginx'
  with_items: [deb, deb-src]

- name: install
  sudo: true
  apt: pkg=nginx state=latest

- name: remove default / example files
  sudo: true
  file: >
    path={{ item }}
    state=absent
  with_items:
    - /etc/nginx/conf.d/default.conf
    - /etc/nginx/conf.d/example_ssl.conf

- name: create sites-enabled
  sudo: true
  file: >
    path=/etc/nginx/sites-enabled
    owner=www-data
    group=www-data
    mode=0755
    state=directory

- name: generate nginx.conf
  sudo: true
  template: >
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
    owner=root
    group=root
    mode=0644
  notify: reload nginx

- name: enable service
  sudo: true
  service: >
    name=nginx
    enabled=true
