- name: copy certificate
  sudo: true
  copy: >
    src={{ router.https.certificate_file }}
    dest=/etc/nginx/{{ router.domain }}.pem
    owner=root
    group=root
    mode=0644
  notify: reload nginx

- name: check if private key file exists locally
  local_action: stat path={{ router.https.private_key_file }}
  register: private_key

- name: copy private key
  sudo: true
  copy: >
    src={{ router.https.private_key_file }}
    dest=/etc/nginx/{{ router.domain }}.key
    owner=root
    group=root
    mode=0600
  notify: reload nginx
  when: private_key.stat.exists

- name: copy dh2048.pem
  sudo: true
  copy: >
    src=dh2048.pem
    dest=/etc/ssl/certs/dh2048.pem
    owner=root
    group=root
    mode=0644
  notify: reload nginx

- name: generate vhost
  sudo: true
  template: >
    src=vhost.j2
    dest=/etc/nginx/sites-enabled/default
    owner=root
    group=root
    mode=0644
  notify: reload nginx
  tags: [configure]
